ktor:
  application:
    modules:
      - cloud.mallne.dicentra.aviator.testserver.ApplicationKt.module
  deployment:
    port: 8080

dicentra:
  behind-proxy: "${BEHIND_PROXY:FALSE}"
  enable-cors: "${ENABLE_CORS:FALSE}"
